services:
  frontend:
    image: walking-buddies-app/frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
      # Isolate node_modules inside container post-initialization
      - /app/node_modules
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app
        - path: ./frontend/package.json
          action: rebuild
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # Must match host machine's local IP address
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.163
    # depends_on:
    #   - backend
  # backend: # Backend not started yet
  #   image: walking-buddies-app/backend
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "3000:3000"